"""Negotiation profile for an emulated gateway (modelled on ER605 v1.0).

Component manifest, capability descriptor and static device-info fields the
controller expects during adoption. Dynamic fields (mac/ip/versions/uptime)
are filled in by GatewayDevice at runtime."""
from __future__ import annotations

COMPONENTS_V2 = {   'abnormalDetect': '1.1',
    'abnormalDt': '1.0',
    'acl': '1.2',
    'aclDisable': '1.0',
    'arpInform': '0.0',
    'arpTable': '1.0',
    'attackDefense': '1.1',
    'bandwidthCtrl': '1.0',
    'client': '0.0',
    'clientInform': '0.0',
    'clientIpBinding': '1.0',
    'clientOpt': '0.0',
    'clientTrafficRequire': '0.0',
    'configVersion': '0.0',
    'connect': '1.0',
    'controllerInfo': '0.0',
    'ctTable': '1.0',
    'ddns': '1.1',
    'ddnsStats': '1.0',
    'devInform': '0.0',
    'dst': '0.0',
    'echoServer': '1.0',
    'facebookV2': '1.1',
    'firewallConfig': '1.0',
    'hwOffload': '1.0',
    'igmp': '1.1',
    'informInterval': '1.1',
    'ipGroup': '1.0',
    'ipMacBinding': '1.0',
    'ipPortGroup': '1.0',
    'ipsecFailover': '1.1',
    'iptv': '1.1',
    'iptv_hw': '1.0',
    'ipv6Group': '1.0',
    'led': '1.0',
    'lldp': '1.0',
    'logInform': '0.0',
    'mdns': '1.1',
    'mirror': '1.0',
    'natAlg': '1.0',
    'natPf': '1.0',
    'network': '1.0',
    'networkTraffic': '0.0',
    'oneToOneNat': '1.0',
    'onlineDetection': '1.1',
    'policyRouting': '1.1',
    'port': '1.0',
    'portInfo': '0.0',
    'portalAct': '0.0',
    'portalDuration': '1.0',
    'portalFreePolicy': '1.0',
    'portforward': '1.0',
    'privacyPolicy': '1.0',
    'qos': '1.0',
    'rebootSchedule': '1.0',
    'routingTable': '1.0',
    'serviceType': '1.0',
    'sessionLimit': '1.0',
    'sideParams': '1.0',
    'snmp': '1.0',
    'snmpAdvance': '1.0',
    'speedDuplex': '1.0',
    'speedTest': '1.0',
    'ssh': '1.0',
    'staticRouting': '1.0',
    'system': '0.0',
    'time': '0.0',
    'timeRange': '0.0',
    'trafficStat': '0.0',
    'upnp': '1.0',
    'urlFiltering': '1.1',
    'userAcnt': '0.0',
    'vpn': '1.3',
    'vpnUsers': '1.1',
    'wanBasicSetting': '1.0',
    'wanIpv4': '1.2',
    'wanIpv6': '1.0',
    'wanLoadBalance': '1.0',
    'wanMac': '1.0'}

DEV_CAP = {   'defaultIgmpWan': 1,
    'extraPortInfos': [],
    'ipsecNum': 20,
    'mandatoryPorts': [],
    'maxSslVpnUserConcurrentNum': 100,
    'maxVpnUserConcurrentNum': 100,
    'portInfos': [   {   'defaultSpeedDuplex': '0:0',
                         'maxBandwidth': 1000,
                         'mode': 0,
                         'name': 'WAN',
                         'port': 1,
                         'speedDuplexList': ['0:0', '1:1', '1:2', '2:1', '2:2', '3:2'],
                         'supportInternetVlan': 1,
                         'supportIptv': 1,
                         'supportMirror': 1,
                         'supportPoe': 0,
                         'type': 0},
                     {   'defaultSpeedDuplex': '0:0',
                         'maxBandwidth': 1000,
                         'mode': 1,
                         'name': 'WAN/LAN1',
                         'port': 2,
                         'speedDuplexList': ['0:0', '1:1', '1:2', '2:1', '2:2', '3:2'],
                         'supportInternetVlan': 1,
                         'supportIptv': 1,
                         'supportMirror': 1,
                         'supportPoe': 0,
                         'type': 1},
                     {   'defaultSpeedDuplex': '0:0',
                         'maxBandwidth': 1000,
                         'mode': 1,
                         'name': 'WAN/LAN2',
                         'port': 3,
                         'speedDuplexList': ['0:0', '1:1', '1:2', '2:1', '2:2', '3:2'],
                         'supportInternetVlan': 1,
                         'supportIptv': 1,
                         'supportMirror': 1,
                         'supportPoe': 0,
                         'type': 1},
                     {   'defaultSpeedDuplex': '0:0',
                         'maxBandwidth': 1000,
                         'mode': 1,
                         'name': 'WAN/LAN3',
                         'port': 4,
                         'speedDuplexList': ['0:0', '1:1', '1:2', '2:1', '2:2', '3:2'],
                         'supportInternetVlan': 1,
                         'supportIptv': 1,
                         'supportMirror': 1,
                         'supportPoe': 0,
                         'type': 1},
                     {   'defaultSpeedDuplex': '0:0',
                         'mode': 1,
                         'name': 'LAN',
                         'port': 5,
                         'speedDuplexList': ['0:0', '1:1', '1:2', '2:1', '2:2', '3:2'],
                         'supportInternetVlan': 1,
                         'supportIptv': 1,
                         'supportMirror': 1,
                         'supportPoe': 0,
                         'type': 2}],
    'specification': {   'aclNum': 64,
                         'bandwidthCtrlNum': 64,
                         'clientIpBindingNum': 1024,
                         'ddnsNum': 24,
                         'ipGroupNum': 512,
                         'ipv6GroupNum': 512,
                         'ldapClassRulesNum': 8,
                         'natPfNum': 32,
                         'networkNum': 128,
                         'policyRoutingNum': 64,
                         'qosClassRulesNum': 32,
                         'serviceTypeNum': 128,
                         'sessionLimitNum': 64,
                         'sslVpnConnectionsNum': 500,
                         'sslVpnLocksNum': 1000,
                         'sslVpnResourceGroupsNum': 128,
                         'sslVpnResourcesNum': 64,
                         'sslVpnUserGroupsNum': 256,
                         'sslVpnUsersNum': 512,
                         'staticRoutingNum': 64,
                         'urlFilteringNum': 64,
                         'vpnIPSecNum': 20,
                         'vpnL2TPClientNum': 10,
                         'vpnOpenVPNNum': 10,
                         'vpnPPTPClientNum': 10,
                         'vpnUsersNum': 240,
                         'wireguardAllPeerNum': 100,
                         'wireguardNum': 20,
                         'wireguardPeerNum': 20},
    'supportAclDisable': 1,
    'supportAllWan': True,
    'supportDiscreteWan': 0,
    'supportIPsecFailover': 1,
    'supportRoutingVpnClient': 1,
    'supportVpnUsb': 0,
    'supportVpnVerify': 1}

DEVICE_MISC = {'extraPortNum': {'extraPort': 0, 'usbLteWan': 0}, 'portNum': 5}

DEVICE_INFO_TEMPLATE = {   'cu': 1,
    'encryptedHwId': '22CA512B4F6AA46358DDE15569E3E93E',
    'encryptedOemId': '9D109CE88890A6A02AC0F21CEA998EEC',
    'extraWanDefaultMacs': [],
    'fac': False,
    'fwVer': '1.3.2 Build 20240528 Rel.73864',
    'hwId': '22CA512B4F6AA46358DDE15569E3E93E',
    'hwVer': 'ER605 v1.0',
    'ip': '192.168.1.1',
    'lanMac': '00-FF-00-12-7A-D4',
    'mask': '255.255.255.0',
    'model': 'ER605',
    'modelId': 0,
    'modelVer': '1.0',
    'mu': 32,
    'oemId': '9D109CE88890A6A02AC0F21CEA998EEC',
    'speeds': [1, 2, 3],
    'time': '0 days 00:03:55',
    'wanDefaultMacs': [   {'defMac': '00-FF-00-12-7A-D5', 'portId': 1},
                          {'defMac': '00-FF-00-12-7A-D6', 'portId': 2},
                          {'defMac': '00-FF-00-12-7A-D7', 'portId': 3},
                          {'defMac': '00-FF-00-12-7A-D8', 'portId': 4}]}
