"""Negotiation profile for an emulated switch (modelled on TL-SG3210 v3.0).

Component manifest, capability descriptor and static device-info fields the
controller expects during adoption. Dynamic fields (mac/ip/versions/uptime)
are filled in by SwitchDevice at runtime."""
from __future__ import annotations

COMPONENTS_V2 = {   'acl': '1.2',
    'arp': '1.0',
    'cliConfig': '1.0',
    'common': '1.0',
    'configVersion': '1.0',
    'controllerInfo': '1.1',
    'devInform': '1.0',
    'deviceDebugInfo': '1.0',
    'dhcpGuard': '1.0',
    'dhcpInform': '1.0',
    'dhcpL2Relay': '1.0',
    'dhcpRelay': '1.0',
    'dhcpServer': '1.0',
    'dhcpv6Guard': '1.0',
    'dot1x': '1.0',
    'eee': '1.0',
    'eventInform': '1.0',
    'fdbInform': '1.0',
    'flowControl': '1.0',
    'igmpSnoop': '1.0',
    'informInterval': '1.1',
    'ipGroup': '1.0',
    'ipPortGroup': '1.1',
    'ipv6Group': '1.0',
    'ipv6PortGroup': '1.0',
    'jumbo': '1.0',
    'lag': '1.1',
    'led': '1.0',
    'lldp': '1.0',
    'logInform': '1.0',
    'loopback': '1.1',
    'loopbackInform': '1.1',
    'macGroup': '1.0',
    'managementVlan': '1.0',
    'mirroring': '1.0',
    'mldSnoop': '1.0',
    'multicastInform': '1.0',
    'network': '1.1',
    'ouiBasedVlan': '1.1',
    'ping': '1.0',
    'port': '1.0',
    'portCommon': '1.0',
    'portInform': '1.0',
    'portIsolation': '1.0',
    'privacyPolicy': '1.0',
    'qosRate': '1.0',
    'routingTable': '1.1',
    'sideParams': '1.0',
    'snmp': '1.0',
    'ssh': '1.0',
    'standaloneMgmt': '1.0',
    'staticRouting': '1.1',
    'stp': '1.0',
    'system': '1.0',
    'terminalSetting': '1.0',
    'time': '1.1',
    'timeRange': '1.0',
    'traceroute': '1.0',
    'transferChannel': '1.0',
    'uiConfigSync': '1.0',
    'upgrade': '1.0',
    'userAcnt': '1.0',
    'vlanIf': '1.1',
    'voiceVlan': '1.0'}

DEV_CAP = {   'comboBeginNum': 0,
    'comboNum': 0,
    'copBeginNum': 1,
    'copNum': 8,
    'cpuTempThreshold': 80,
    'dot1x': 100,
    'feBeginNum': 0,
    'feNum': 0,
    'giBeginNum': 1,
    'giNum': 10,
    'lagMember': 8,
    'lagNum': 8,
    'macTempThreshold': 80,
    'maxMirrorGroup': 1,
    'maxMirroredPort': 9,
    'phyTempThreshold': 80,
    'poePortLimit': 300,
    'poePortNum': 8,
    'portNum': 10,
    'pseTempThreshold': 80,
    'sfpBeginNum': 9,
    'sfpNum': 2,
    'supportClearCounters': 1,
    'teBeginNum': 0,
    'teNum': 0,
    'twBeginNum': 0,
    'twNum': 0,
    'vlan': 4094}

DEVICE_MISC = {'category': 'L2 SWITCH', 'modelType': 'NORMAL', 'portNum': 10}

DEVICE_INFO_TEMPLATE = {   'cu': 0,
    'fac': False,
    'fwVer': '3.0.8 Build20240710 Rel.43970',
    'hwId': '93198DDF77EAF24F93AFD110A07C48AB',
    'hwVer': '3.0',
    'ip': '192.168.0.3',
    'ipv6List': ['fe80::20a:dbff:fee1:ac2a'],
    'model': 'TL-SG3210',
    'modelVer': '3.0',
    'mu': 45,
    'oemId': 'EBBE93F5D7E4DE41DD95F8C510575D7D',
    'sn': '',
    'time': '0 days 05:19:13'}
